### ISSUE TITLE
Crtsh, massdns not running

### ISSUE THREAD

**Issue by d0xo** [Dec0y-jb/enum#1]
crtsh(){
       "$masspath"/scripts/ct.py "$domain" 2>/dev/null > ./temp && cat ./temp | "$masspath"/bin/massdns -r "$masspath"/lists/resolvers.txt -t A -q -o S -w ./crtsh.tmp
}

mass(){
        "$masspath"/scripts/subbrute.py "$enumpath"/enum.txt "$domain" | "$masspath"/bin/massdns -r "$masspath"/lists/resolvers.txt -t A -q -o S -w ./massdns.tmp 2>/dev/null
}

Are these running? of them (it does not work to add them)
Sublister has python on the line to run the py file but nothing on these lines, don't work to add them either tho

But I have sent thousands of domains, nothing from these on either of the domains

**Comment by Dec0y-jb** [comment]
I'll need more specifics. These are working fine for me. There are some issues with crt.sh in general where if there are too many subdomains found, it will 404 causing the hang. What's happening? Is it skipping them? Saying 0 results? Is it hanging forever? What domains are you searching for?

**Comment by Dec0y-jb** [comment]
Any error messages would be helpful, precise steps to reproduce, what you're seeing for output, etc. Also - if you've modified the source code at all, then this could be causing problems. Are you using a complete unaltered clone? Have you modified the path variables at all?

**Comment by d0xo** [comment]
The result is 0 for both crtsh and massdns, all the time. No other errors
I have updated the .sh file with your code several times.

It does still not work.

**Comment by Dec0y-jb** [comment]
I just made a new change that corrected crt.sh. There must have been a change in Python 2.7 that removed the request library by default. I changed it to a python3 call and that resolved the issue. Can you confirm? For certspotter - it works fine for me. Although you might have hit your limit without an API key. Try to run the curl command from the CLI outside the script and see if anything is returned.

**Comment by Dec0y-jb** [comment]
Fixed in latest commit.
